[ADD] inventory_new_columns
masbha-tex/taps pull request #9
Opened 2021-06-09 03:42 UTC by nni-odoo

Adding Total Landed Cost, Unit Value and Total Unit Value into stock.quant list view.

2523902

2021-06-09 03:50 UTC, fja-odoo requested changes
As usual lots of comment remains, please remove them.
Also if a comment is useful, put it on top of the line not at the end.

2021-06-09 03:50 UTC, fja-odoo commented on inventory_new_columns/models/stock_production_lot.py
> +        products = self.browse()
products ? should be lots

2021-06-09 03:50 UTC, fja-odoo commented on inventory_new_columns/models/stock_production_lot.py
> +            if not move.lot_ids:
Add this to the domain instead: `('stock_move_id.lot_ids', '!=', False)`

2021-06-09 03:50 UTC, fja-odoo commented on inventory_new_columns/models/stock_production_lot.py
> +            move = self.env['stock.move'].browse(group['stock_move_id'][0])
Group the ids and do this all at once ?

2021-06-09 03:50 UTC, fja-odoo commented on inventory_new_columns/models/stock_production_lot.py
> +            move_lines = move.move_line_ids.read_group(domain_2, ['qty_done:sum'], groupby=['lot_id'])
Do this outside of the loop for all move_lines of all moves at once.

2021-06-09 03:50 UTC, fja-odoo commented on inventory_new_columns/models/stock_production_lot.py
> +                lot = self.env['stock.production.lot'].browse(line['lot_id'][0])
`self` are already stock.production.lot you should rely on it instead of browsing again.

2021-06-09 03:50 UTC, fja-odoo commented on inventory_new_columns/models/stock_quant.py
> +                qty_sum = sum(self.env['stock.quant'].search([('lot_id', '=', quant.lot_id.id), ('location_id.usage', '=', 'internal')]).mapped('quantity'))
read_group instead of search in for loop ?

2021-06-09 04:09 UTC, nni-odoo commented on inventory_new_columns/models/stock_production_lot.py
> +        products = self.browse()
going to remove it, just realised it's not being used anywhere.

2021-06-09 11:22 UTC, fja-odoo requested changes

2021-06-09 11:22 UTC, fja-odoo commented on inventory_new_columns/models/stock_production_lot.py
> +        moves = [i['stock_move_id'][0] for i in groups if Move.browse(i['stock_move_id'][0]).lot_ids]
Isn't there a way to not loop 2 time over all records in groups ?

2021-06-10 00:26 UTC, nni-odoo commented on inventory_new_columns/models/stock_production_lot.py
> +        move_sum = dict((i['stock_move_id'][0], i['value']) for i in groups)  # move: landed_cost value
I think since stock_move_id and product_id is one-to-one, it will be summed up. I did a ['value:sum'] as well on the read group

2021-06-10 03:02 UTC, fja-odoo requested changes

2021-06-10 03:02 UTC, fja-odoo commented on inventory_new_columns/models/stock_production_lot.py
> +        move_sum = dict((i['stock_move_id'][0], i['value']) for i in groups)
Couldn't `move_sum` contain directly `move.quantity_done * i['value']`
This way you browse the move only once.

2021-06-10 03:42 UTC, fja-odoo approved these changes
If you could just rename the module with a better name like `Inventory_landed_cost`
And update the manifest name and summary
Then good to rebase and merge.

2021-06-10 03:42 UTC, fja-odoo commented on inventory_new_columns/models/stock_production_lot.py
> +        lot_move_value = dict((i['lot_id'][0], (i['qty_done'], i['move_id'][0])) for i in lot_group)  # lot:(qty_done, move_id)
remove comment

2021-06-10 03:50 UTC, merged